### ISSUE TITLE
Does not work on Lubuntu 3.1.1

### ISSUE THREAD

**Issue by tosiara** [LeMaker/WiringBP#1]
Steps to reproduce:
1. Flash latest Lubuntu 3.1.1 (2014-08-07, kernel 3.4.90)
2. Get WiringBPI sources, build and install wiringpi: ./build
3. Connect DHT11
4. Sensor does not work

Initial discussion: http://forum.lemaker.org/forum.php?mod=redirect&goto=findpost&ptid=353&pid=40497&fromuid=17962

To workaround you can take the library from working image - Raspbian 3.1. Compile against that library - and sensor will work:

```
# gcc -o dht11 mydht11.c -L/home/bananapi -lwiringPi
# LD_PRELOAD=/home/bananapi/libwiringPi.so ./dht11
```

So Raspbian 3.1 delivers working binary, while library built from sources does not work

**Comment by Tony-HIT** [comment]
I have tried compile the wiringPi under Lubuntu 3.1.1, it works. Do you mean the whole wiringPi function not work on Lubuntu, or just the DHT11 not work?

**Comment by tosiara** [comment]
I only tested DHT11 with data wire connected to GPIO1 pin#12

**Comment by Tony-HIT** [comment]
Can the gpio readall can work on Lubuntu??? If it work, it says the wiringPi library is well.

**Comment by tosiara** [comment]
How can I check that? Is there an easy way to verify?
