### ISSUE TITLE
WiringPi internal Pull Up/Down Reversing

### ISSUE THREAD

**Issue by 4Joe** [LeMaker/WiringBP#5]
Hello,
i try to compile the source wiringpi for banana pi branch in github, the result was incorect status for pull up/down control. Next trial using the banana pro branch in banana pi board, The pull up/down issue has gone, but the pin definition become un sorted as the boad definition di docs.

**Comment by Tony-HIT** [comment]
I know this issue. I have fixed it in pro branch, but foget fix in pi
branch. I am on a vacation now, will fix it after my vacation. But you can
also refer to the pro code commit to fix it first
2015年2月16日 17:12于 "4Joe" <notifications@github.com>写道：

**Comment by Tony-HIT** [comment]
I have fix the problem in bananapi branch, see the latest commit, please try and test it.

**Comment by 4Joe** [comment]
Ok many thank for your kindness :)
I will try it

Regards,
