### ISSUE TITLE
WiringBP on Banana pro set mode as pull-down

### ISSUE THREAD

**Issue by iamsven** [LeMaker/WiringBP#8]
I have an issue with the gpio utility. Everything works fine except the command to enable the pull-down resistor for a pin. If I execute the following command: 

``` shell
gpio mode 7 down
```

nothing happens, an the pin is still floating. (The pull-up command works fine, btw.)

If I take a look in the correspondig pin-file, after executing the set pull-down command, under 

``` shell
/sys/class/gpio/gpio4/pull
```

it says "unkown", if I set it manually to "down" everything is working as it should, so I guess there is an issue in the WiringBP lib or is it just me?

**Comment by tab-liu** [comment]
well, I use lubuntu on Banana Pro, and I didnt see this problem. When I run 'gpio mode 7 down', the LED(connect to the pin) turned off. Try to update you WiringBP?

**Comment by iamsven** [comment]
I have the newest version of WiringBP.
The problem occurs if I have a switch connected and the switch is open. (LED's work fine, too.)

**Comment by savageautomate** [comment]
I just encountered the same issue.  The PULL_DOWN does not seem to be working.
I'm using the "bananapro" branch on a BananaPro board.

```
bananapi@bpipro $ gpio mode 2 up
bananapi@bpipro $ cat /sys/class/gpio/gpio27/pull
up
bananapi@bpipro $ gpio mode 2 down
bananapi@bpipro $ cat /sys/class/gpio/gpio27/pull
unknown
```

**Comment by savageautomate** [comment]
Pull Requests submitted to fix this issue:

**BananaPro**  (branch _bananapro_)
Pull Request: https://github.com/LeMaker/WiringBP/pull/10    --- **MERGED**

**BananaPi**    (branch _bananapi_)
Pull Request: https://github.com/LeMaker/WiringBP/pull/11    --- **MERGED**
